import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header.component";
import Footer from "@/components/footer.component";
import localFont from 'next/font/local'

const hasweny = localFont({
  src: '../../public/fonts/hasweny.otf',
  variable: '--font-hasweny'
})

// Si quieres mantener Modern No. 20 de Google Fonts
import { Inter } from 'next/font/google'
const modern = Inter({
  subsets: ['latin'],
  variable: '--font-modern'
})

export const metadata: Metadata = {
  title: "Nunca jamas",
  description: "Generated by wadepar6",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hasweny.variable} ${modern.variable} antialiased font-modern`}
      >
        <Header />
        <main className="bg-gray-200 text-black">
          <div id="content-wrapper" className="container mx-auto">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}